bump cli version
mhiew/redoc-lint-github-action pull request #3
Opened 2022-12-15 21:22 UTC by dogmatic69

The old package is also depreciated so replaced with the new one

2024-02-15 11:19 UTC, bbrks requested changes
Been a while since this PR and it's out of beta now!

2024-02-15 11:19 UTC, bbrks commented on Dockerfile
> +RUN ["npm", "install", "-g", "@redocly/cli@1.0.0-beta.117"]
```suggestion
RUN ["npm", "install", "-g", "@redocly/cli@1.9.0"]
```

2024-02-16 02:17 UTC, mhiew commented
sorry I missed this originally.
hopefully this is addressed in the latest v4 release
https://github.com/mhiew/redoc-lint-github-action/releases/tag/v4

2024-02-16 02:17 UTC, closed without merging

2024-02-16 13:11 UTC, bbrks commented
Thank you!